# Generated by Django 3.1.7 on 2021-03-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiction_subject', models.CharField(max_length=100)),
                ('fiction_text', models.TextField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_create_time', models.DateTimeField()),
                ('fiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.fiction')),
            ],
        ),
    ]
