# Generated by Django 3.1.7 on 2021-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_create_time',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiction',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
