# Generated by Django 3.1.7 on 2021-03-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='fiction',
        ),
    ]
