# Generated by Django 3.1.7 on 2021-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_reply_fiction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
